# Generated by Django 6.0.7 on 2026-08-02 00:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateField(default=django.utils.timezone.localdate)),
                ('tablon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablon_app.tablon')),
            ],
        ),
    ]
