# Generated by Django 6.0.7 on 2026-08-02 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hora_publicacion",
            field=models.TimeField(default=django.utils.timezone.localtime),
        ),
    ]
