# Generated by Django 6.0.7 on 2026-08-07 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0002_post_hora_publicacio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts_app.post')),
            ],
        ),
    ]
