# Generated by Django 6.0.7 on 2026-08-07 03:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0003_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fecha_publicacion',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='comentario',
            name='hora_publicacion',
            field=models.TimeField(default=django.utils.timezone.localtime),
        ),
    ]
