[project]
name = "vomiting-things-prj"
version = "0.1.0"
description = "Proyecto de foro 4chan-like"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django==6.0.7",
    "django-stubs==6.0.7",
]

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]

# Ubicacion desde donde debe empezar a indexar dependencias o buscar directorios
search-path = ["."]

# Ubicación del codigo/logica del proyecto (Para el mapeado de modulos e importaciones locales)
source-roots = ["src"]