# Generated by Django 6.0.7 on 2026-08-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tablon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_tablon', models.CharField(max_length=20)),
                ('simbolo', models.CharField(max_length=5)),
            ],
        ),
    ]
