# Generated by Django 6.0.7 on 2026-08-02 00:47

from django.db import migrations


def carga_data_tablon(apps, scheme_editor):
    Tablon = apps.get_model("tablon_app", "Tablon")
    data = [
        {
            "nombre_tablon": "videojuegos",
            "simbolo": "v",
        },
        {
            "nombre_tablon": "internet",
            "simbolo": "i",
        },
        {
            "nombre_tablon": "animé",
            "simbolo": "a",
        },
        {
            "nombre_tablon": "tecnología y programación",
            "simbolo": "tp",
        },
        {
            "nombre_tablon": "random",
            "simbolo": "b",
        },
    ]

    for d in data:
        # El metodo busca filtrando por un campo especifico, si no existe el objeto, lo crea
        Tablon.objects.get_or_create(nombre_tablon=d["nombre_tablon"], defaults=d)


class Migration(migrations.Migration):
    dependencies = [
        ("tablon_app", "0001_initial"),
    ]

    operations = [migrations.RunPython(carga_data_tablon)]
